---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - gem update bundler
before_script:
  - bundle exec rake spec_prep
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
    script: bundle exec rake beaker
    services: docker
    sudo: required
notifications:
  email: false
